WITH CTE AS (
    SELECT TO_TIMESTAMP(STARTED_AT) as STARTED_AT,
    DATE(TO_TIMESTAMP(STARTED_AT)) as DATE_STARTED_AT,
    HOUR(TO_TIMESTAMP(STARTED_AT)) as HOUR_STARTED_AT,
    
    {{get_day_type('STARTED_AT')}}AS DAY_TYPE,
    {{get_seasons('STARTED_AT')}} as SEASON,
    {{function1('STARTED_AT')}} as CURRENT_OR_PAST

    FROM {{ source ('DEMO', 'BIKE') }} 

)
SELECT * FROM CTE