WITH TRIPS AS (
    SELECT 
        RIDE_ID,
        DATE(TO_TIMESTAMP(STARTED_AT)) AS TRIP_DATE,
        START_STATION_ID AS START_STATION_ID,
        END_STATION_ID,
        MEMBER_CASUAL AS MEMEBER_CASUAL,
        TIMESTAMPDIFF(SECOND, TO_TIMESTAMP(STARTED_AT), TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION_SECONDS,
        
    FROM {{ ref('stage_bike') }}
    LIMIT 100
)
SELECT * FROM TRIPS